apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: listmonk
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
configMapGenerator:
  - name: supabase-ca
    files:
      - supabase-root-2021.crt
