global:
  scrape_interval: 15s
  external_labels:
    monitor: "docker-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ["node_exporter:9100"]

rule_files:
- "alert.rules"
