################################################################
# Web configuration backend
################################################################
[web]
address = ":1111"
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "docker.in.bb8.fun"
watch = true