defaultEntryPoints = ["http", "https"]
[entryPoints]
[entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
[entryPoints.https]
  address = ":443"
  # This is required for ACME support
  [entryPoints.https.tls]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "bb8.fun"
  watch = true
  exposedbydefault = false

[file]
[backends]

[backends.ebooks]
[backends.ebooks.servers.default]
  url = "http://192.168.1.111:2202"

# This is currently not exposed
# Since I can't apply a authentication
# on this yet
[backends.elibsrv]
[backends.elibsrv.servers.default]
  url = "http://elibsrv.captnemo.in:90"

[backends.scan]
[backends.scan.servers.default]
  url = "http://scan.in.bb8.fun:90"

[frontends]

[frontends.ebooks]
  backend = "ebooks"
  passHostHeader = true
  [frontends.ebooks.headers]
    SSLRedirect = true
    SSLTemporaryRedirect = true
    STSSeconds = 2592000
    ContentTypeNosniff = true
    BrowserXssFilter = true
    ReferrerPolicy = "no-referrer"
  [frontends.ebooks.headers.customrequestheaders]
    X-Forwarded-Proto = "https"
  [frontends.ebooks.headers.customresponseheaders]
    X-Powered-By = "Allomancy"
    Server = "BlackBox"
    X-Clacks-Overhead = "GNU Terry Pratchett"
  [frontends.ebooks.routes.domain]
    rule = "Host:ebooks.in.bb8.fun,ebooks.bb8.fun"

[frontends.scan]
  backend = "scan"
  [frontends.scan.headers]
    SSLRedirect = true
    SSLTemporaryRedirect = true
    STSSeconds = 2592000
    FrameDeny = true
    ContentTypeNosniff = true
    BrowserXssFilter = true
    ReferrerPolicy = "no-referrer"
  [frontends.scan.headers.customresponseheaders]
    X-Powered-By = "Allomancy"
    Server = "BlackBox"
    X-Clacks-Overhead = "GNU Terry Pratchett"
[frontends.scan.routes.domain]
  rule = "Host:scan.bb8.fun"

[web]
  address = ":1111"
  readOnly = true

[acme]

email = "acme@captnemo.in"
storage = "/acme/acme.json"
entryPoint = "https"
dnsProvider = "cloudflare"
onHostRule = false
onDemand   = false

# Waiting till Jan '18 to get wildcard SSL on LE
[[acme.domains]]
main = "in.bb8.fun"
sans = ["emby.in.bb8.fun", "airsonic.in.bb8.fun", "muximux.in.bb8.fun", "home.in.bb8.fun"]

[[acme.domains]]
main = "bb8.fun"
sans = [
  "transmission.bb8.fun",
  "emby.bb8.fun",
  "flexget.bb8.fun",
  "couchpotato.bb8.fun",
  "traefik.bb8.fun",
  "airsonic.bb8.fun",
  "headphones.bb8.fun",
  "wiki.bb8.fun",
  "muximux.bb8.fun",
  "home.bb8.fun",
  "ebooks.bb8.fun",
]


