defaultEntryPoints = ["http", "https"]
[entryPoints]
[entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
[entryPoints.https]
  address = ":443"
  # This is required for ACME support
  [entryPoints.https.tls]
  [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/git.captnemo.in.crt"
    keyFile  = "/etc/traefik/git.captnemo.in.key"
  [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/rss.captnemo.in.crt"
    keyFile  = "/etc/traefik/rss.captnemo.in.key"

[docker]
  # Make sure you mount this as readonly
  endpoint = "unix:///var/run/docker.sock"
  domain = "bb8.fun"
  watch = true
  exposedbydefault = false

[file]
[backends]

# This is currently not exposed
# Since I can't apply a authentication
# on this yet
[backends.elibsrv]
[backends.elibsrv.servers.default]
  url = "http://elibsrv.captnemo.in:90"

[backends.scan]
[backends.scan.servers.default]
  url = "http://scan.in.bb8.fun:90"

[frontends]

[frontends.scan]
  backend = "scan"
  [frontends.scan.headers]
    SSLRedirect = true
    SSLTemporaryRedirect = true
    STSSeconds = 2592000
    FrameDeny = true
    ContentTypeNosniff = true
    BrowserXssFilter = true
    ReferrerPolicy = "no-referrer"
  [frontends.scan.headers.customresponseheaders]
    X-Powered-By = "Allomancy"
    Server = "BlackBox"
    X-Clacks-Overhead = "GNU Terry Pratchett"
[frontends.scan.routes.domain]
  rule = "Host:scan.bb8.fun"

[web]
  address = ":1111"
  readOnly = true

[acme]

email = "acme@captnemo.in"
storage = "/acme/acme.json"
entryPoint = "https"
dnsProvider = "cloudflare"
onHostRule = true
onDemand   = false
acmelogging = true

# Waiting till Jan '18 to get wildcard SSL on LE

[[acme.domains]]
main = "bb8.fun"
sans = [
  "airsonic.bb8.fun",
  "airsonic.in.bb8.fun",
  "cadvisor.bb8.fun",
  "couchpotato.bb8.fun",
  "debug.in.bb8.fun",
  "ebooks.bb8.fun",
  "ebooks.in.bb8.fun",
  "emby.bb8.fun",
  "emby.in.bb8.fun",
  "flexget.bb8.fun",
  "git.bb8.fun",
  "gitea.bb8.fun",
  "grafana.bb8.fun",
  "headphones.bb8.fun",
  "home.bb8.fun",
  "home.in.bb8.fun",
  "library.bb8.fun",
  "luke.bb8.fun",
  "monitoring.bb8.fun",
  "muximux.bb8.fun",
  "muximux.in.bb8.fun",
  "pics.bb8.fun",
  "pics.in.bb8.fun",
  "read.bb8.fun",
  "read.in.bb8.fun",
  "rey.bb8.fun",
  "scan.bb8.fun",
  "tatooine.bb8.fun",
  "traefik.bb8.fun",
  "transmission.bb8.fun",
  # "transmission.in.bb8.fun",
  "wiki.bb8.fun"
]
