defaultEntryPoints = ["http", "https"]
sendAnonymousUsage = false
checkNewVersion = false
[web]
address = ":1111"
readOnly = true
[web.statistics]
[traefikLog]
[accessLog]

[entryPoints]
[entryPoints.http]
  address = ":80"
[entryPoints.https]
  address = ":443"
  # This is required for ACME support
  [entryPoints.https.tls]
  [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/star.bb8.fun.crt"
    keyFile = "/etc/traefik/star.bb8.fun.key"
  [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/git.captnemo.in.crt"
    keyFile  = "/etc/traefik/git.captnemo.in.key"
  [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/rss.captnemo.in.crt"
    keyFile  = "/etc/traefik/rss.captnemo.in.key"
  [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/tatooine.club.crt"
    keyFile  = "/etc/traefik/tatooine.club.key"

[docker]
  # NOTE: readonly doesn't reduce the risk because
  # it is a unix socket - it doesn't automatically translate
  # read|write perms to GET/POST requests.
  endpoint = "unix:///var/run/docker.sock"
  domain = "bb8.fun"
  watch = true
  exposedbydefault = false

[file]
[backends]

# To enable Traefik to export internal metrics to Prometheus
[web.metrics.prometheus]
